# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' A matrix-based RcppArmadillo implementation for computing x'Ay //'
#' @param x A size n vector
#' @param y A size m vector
#' @param A A size (n x m) matrix
#' @return A scalar value evaluating x'Ay 
#' @export
GECKO <- function(n1in, n2in, nsin, LDscorein, Zscorein, Annotation_labelin, Weightin, Fix_Vein, Test) {
    .Call(`_GECKO_GECKO`, n1in, n2in, nsin, LDscorein, Zscorein, Annotation_labelin, Weightin, Fix_Vein, Test)
}

